import type { ValidationError } from "../cli/validate.js";
import type { GeneratorResult } from "./types.js";

type GeneratorErrorCode =
  | "ARGUMENT_INVALID"
  | "ARTIFACT_FORMAT_INVALID"
  | "DOCUMENT_NOT_REVIEWABLE"
  | "PLACEHOLDER_REMAINS"
  | "SPLIT_GROUP_INVALID"
  | "INTERNAL_ERROR";

const ERROR_TEXT: Readonly<Record<GeneratorErrorCode, readonly [string, string]>> = {
  ARGUMENT_INVALID: [
    "The generator input does not match the supported interface.",
    "Provide the exact documented generator arguments.",
  ],
  ARTIFACT_FORMAT_INVALID: [
    "Generated bytes do not match the frozen artifact grammar.",
    "Regenerate both artifacts from the validated review document and frozen template.",
  ],
  DOCUMENT_NOT_REVIEWABLE: [
    "The review document still contains initialization-only draft content.",
    "Replace every draft decision slot and explicitly set a valid review lifecycle state.",
  ],
  PLACEHOLDER_REMAINS: [
    "A frozen generator token remains unresolved.",
    "Use the complete frozen template and fill each data token exactly once.",
  ],
  SPLIT_GROUP_INVALID: [
    "The split delivery is incomplete or internally inconsistent.",
    "Provide every consecutive part with unique identities, base names, and portable paths.",
  ],
  INTERNAL_ERROR: [
    "Generation stopped because of an unexpected internal error.",
    "Retry from validated inputs; if the failure repeats, inspect the local installation.",
  ],
};

function safePath(path: string): string {
  return path === "" || (path.startsWith("/") && !path.includes("\0")) ? path : "/";
}

export function generatorError(code: GeneratorErrorCode, path: string): ValidationError {
  const [message, hint] = ERROR_TEXT[code];
  return { code, path: safePath(path), blockId: null, message, hint };
}

export function generatorFailure<T = never>(
  errors: readonly ValidationError[],
): GeneratorResult<T> {
  return {
    ok: false,
    errors: [...errors].sort((left, right) => {
      if (left.path !== right.path) return left.path < right.path ? -1 : 1;
      return left.code < right.code ? -1 : left.code > right.code ? 1 : 0;
    }),
  };
}

export function generatorSuccess<T>(value: T): GeneratorResult<T> {
  return { ok: true, value };
}
